## Numpy => Numerical Python 
=> It is Python Library 
=> large number -Manipulate,mathematical Operation



In [2]:
a=[1,2,3,4]
print(a[2])

3


- pip => Python Install Packer => to install python Dependencies 

In [4]:
! pip install numpy


[notice] A new release of pip is available: 25.2 -> 26.2.1
[notice] To update, run: python.exe -m pip install --upgrade pip


In [6]:
! pip show numpy

Name: numpy
Version: 2.5.1
Summary: Fundamental package for array computing in Python
Home-page: https://numpy.org
Author: Travis E. Oliphant et al.
Author-email: 
License-Expression: BSD-3-Clause AND 0BSD AND MIT AND Zlib AND CC0-1.0
Location: C:\Users\DELL\AppData\Local\Programs\Python\Python314\Lib\site-packages
Requires: 
Required-by: pandas


In [7]:
## List Vs Numpy 
- Numpy Fast 

SyntaxError: invalid syntax (2397411106.py, line 2)

In [8]:
import numpy as np

In [9]:
a=[1,2,3,4]
print(type(a))

<class 'list'>


In [10]:
a=np.array([1,2,3,4,5])
print(type(a))

<class 'numpy.ndarray'>


In [17]:
import time
a=[1,2,3,4]
start_time=time.time() 
print([i*2 for i in a ])
end_time=time.time() 

print("Time Taken ",end_time-start_time)

[2, 4, 6, 8]
Time Taken  0.0006661415100097656


In [18]:
a=[1,2,3,4]
start_time=time.time() 
a=np.array(a)
print(a*2)
end_time=time.time() 

print("Time Taken ",end_time-start_time)

[2 4 6 8]
Time Taken  0.0030515193939208984


In [12]:
print([10,20,30]*2)

[10, 20, 30, 10, 20, 30]


In [14]:
print([10,20,30]+[2,4,6])

[10, 20, 30, 2, 4, 6]


In [19]:
a=[10,20,30]
print(a)
print(np.array(a))

[10, 20, 30]
[10 20 30]


In [22]:
a=np.array([
    [10,20,30],
[20,30,40]]
)
a.shape

(2, 3)

In [23]:
a=np.array([
    [10,20],
[20,30,40]]
)
a.shape

ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 1 dimensions. The detected shape was (2,) + inhomogeneous part.

In [26]:
a=np.array([
    [10,20],
[20,30],
[40,50]]
)
print(a)
a.shape

[[10 20]
 [20 30]
 [40 50]]


(3, 2)

In [31]:
a=np.array([[10,20,30,40,50],[10,20,30,40,50]])
print(a.shape)
a.ndim

(2, 5)


2

In [29]:
a=np.array([[[10,20,30,40,50],[10,20,30,40,50]],[[10,20,30,40,50],[10,20,30,40,50]]])
print(a)
a.shape
a.ndim


[[[10 20 30 40 50]
  [10 20 30 40 50]]

 [[10 20 30 40 50]
  [10 20 30 40 50]]]


3

In [33]:
a=np.array([1,3,5,7])
print(type(a))
a.dtype


<class 'numpy.ndarray'>


dtype('int64')

In [35]:
a=np.array([1,2.5,3,4.5,"apple",True])
print(a)
a.dtype

['1' '2.5' '3' '4.5' 'apple' 'True']


dtype('<U32')

In [36]:
a=np.array([1,2.5,3,4.5])
print(a)
a.dtype

[1.  2.5 3.  4.5]


dtype('float64')