In [1]:
import numpy as np

### function
- Aggregate function
- Type Convertion
- indexing and slicing

In [2]:
a=[1,2,3,4,5]
sum(a)

15

In [3]:
a=[1,2,3,4,5]
arr=np.array(a)
np.sum(arr)

np.int64(15)

In [8]:
a=np.random.randint(10,20,size=5)
a

array([16, 11, 16, 14, 17], dtype=int32)

In [9]:
print(a)

[16 11 16 14 17]


In [10]:
np.min(a)

np.int32(11)

In [11]:
np.max(a)

np.int32(17)

In [13]:
list(range(6))

[0, 1, 2, 3, 4, 5]

In [14]:
list(range(0,6,2))


[0, 2, 4]

In [16]:
print(np.arange(5))

[0 1 2 3 4]


In [17]:
np.arange(5)

array([0, 1, 2, 3, 4])

In [18]:
list(range(5,0,-1))

[5, 4, 3, 2, 1]

## type convertion 
- convert one data type to another
- Implicit (automatic )
- Explicit


In [20]:
a="11"
print(int(a))

11


In [21]:
a="flower"
print(int(a))

ValueError: invalid literal for int() with base 10: 'flower'

In [22]:
a="+10"
print(int(a))

positive, +, negative (-) 

10


In [23]:
a="a10"
print(int(a))

ValueError: invalid literal for int() with base 10: 'a10'

In [24]:
a="10a"
print(int(a))

ValueError: invalid literal for int() with base 10: '10a'

In [25]:
a=10
b=15.9
print(a+b)

25.9


Explicit  we can do it in 2 places 
1.  at the time of Create array Element 
2. convertion

In [26]:
arr=np.array([10,20,30])
arr.dtype

dtype('int64')

In [29]:
# type 1  using dtype
arr=np.array([10,20,30],dtype=np.int8)
print(arr)
print(arr.dtype)

[10 20 30]
int8


In [32]:
# type 2 using astype
a=[2,4,6,8]
a=np.array(a).astype('int8')
a.dtype



dtype('int8')

In [34]:
a=[120,300,1,2,3]
a=np.array(a,dtype=np.int8)
print(a)
print(a.dtype)

# - 128 0 127

OverflowError: Python integer 300 out of bounds for int8

In [35]:
a=[-129,10,1,2,3]
a=np.array(a,dtype=np.int8)
print(a)
print(a.dtype)

OverflowError: Python integer -129 out of bounds for int8

In [37]:
a=[120,301,1,2,3]
a=np.array(a).astype('int8')
a  # 301-256

array([120,  45,   1,   2,   3], dtype=int8)

In [39]:
301-256

45

In [42]:
a=[-129,10,1,2,3]
a=np.array(a).astype('int8')
a # 256-129

array([127,  10,   1,   2,   3], dtype=int8)

In [41]:
256-129

127

In [43]:
###indexing

In [44]:
arr=np.arange(1,6)
arr

array([1, 2, 3, 4, 5])

In [46]:
arr[2],arr[-3]

(np.int64(3), np.int64(3))

In [57]:
a=np.array([[1,2],[3,4]])
print(a.shape)
print(a.ndim)
print(a[1][0])
print(a[1,0])
print(a[0])
print(a[1])
print(a[-1])

(2, 2)
2
3
3
[1 2]
[3 4]
[3 4]


In [58]:
a=np.array([[1,2],[3,4,5]])

ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 1 dimensions. The detected shape was (2,) + inhomogeneous part.

In [61]:
a=np.array(np.arange(1,13))
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

- 4*3
- 3*4
- 6*2
- 2*6
- 1*12
- 12*1

In [63]:
a=np.array(np.arange(1,13)).reshape(4,3)
a

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [64]:
a=np.array(np.arange(1,13)).reshape(2,6)
a

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12]])

In [65]:
a=np.array(np.arange(1,13)).reshape(4,-1)
a

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [66]:
a=np.array(np.arange(1,13)).reshape(-1,4)
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [67]:
a=np.array(np.arange(1,13)).reshape(-1,-1)
a

ValueError: can only specify one unknown dimension

In [68]:
a=np.array(np.arange(1,14)).reshape(3,-1)
a

ValueError: cannot reshape array of size 13 into shape (3,newaxis)

In [70]:
a=np.array(np.arange(1,14)).reshape(-1,13)
a

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13]])