# introduction
- Numpy stands for Numerical Python 
- it is a powerful library for working with numbers,arrays and mathematical Operations.
- Pandas,Matplotlib,scikit-learn - all of them are built on top of Numpy 

In [1]:
# List vs Numpy 

# ! pip install numpy
# ! pip show numpy
! pip show numpy

Name: numpy
Version: 2.5.1
Summary: Fundamental package for array computing in Python
Home-page: https://numpy.org
Author: Travis E. Oliphant et al.
Author-email: 
License-Expression: BSD-3-Clause AND 0BSD AND MIT AND Zlib AND CC0-1.0
Location: C:\Users\DELL\AppData\Local\Programs\Python\Python314\Lib\site-packages
Requires: 
Required-by: pandas


In [2]:
import numpy as np 


In [3]:
a=[1,2,3,4]
print(type(a))

<class 'list'>


In [6]:
arr=np.array(a)
print(type(a))
print(type(arr))
<class 'numpy.ndarray'> # ndimension array

<class 'list'>
<class 'numpy.ndarray'>


In [7]:
print(a)
print(arr)

[1, 2, 3, 4]
[1 2 3 4]


## List vs Ndarray
- Speed Slow - veryfast 
- memory more - less 
- datatype - hetrogenous - homogeneous
- mathematical operation  Loops - Direct access
- Dimension  1d - nd 

In [8]:
## Speed Comparision 

In [50]:
import numpy as np 
import time 

start=time.time()
my_list =list(range(1000000))
result=[x*2 for x in my_list]
end=time.time() 
print(f"Python List time {end-start:.4f}seconds")


Python List time 0.1722seconds


In [51]:
start=time.time()
my_array =np.arange(1000000)
result=my_array*2
end=time.time() 
print(f"Python array time {end-start:.4f}seconds")

Python array time 0.0407seconds


In [55]:
import sys
print("List Size",sys.getsizeof(list(range(1000000))))
print("Numpy Size",sys.getsizeof(np.arange(1000000)))

List Size 8000056
Numpy Size 8000112


### Math Operation Comparision


In [15]:
import numpy as np 
numbers=[1,2,3,4,5]
doubled =[x*2 for x in numbers]
print(doubled)

[2, 4, 6, 8, 10]


In [18]:
arr=np.array([1,2,3,4,5])
doubled=arr*2
print(doubled)
print(arr/2)
print(arr//2)

[ 2  4  6  8 10]
[0.5 1.  1.5 2.  2.5]
[0 1 1 2 2]


In [19]:
arr=np.array([1,2,3,4,5])
print(arr)
print(type(arr))

[1 2 3 4 5]
<class 'numpy.ndarray'>


# Basic array information


## 1. shape
### Basic Array Structure Rules
**arr.shape**
- A NumPy array should have a regular structure.
- Elements at the same level should have the same length.
- For a 2D array, every row should have the same number of elements.
- For a 3D array, every block should have the same number of rows and columns.
- If the structure is not consistent, NumPy may show:inhomogeneous shape after 1 dimensions


In [36]:
arr1=np.array([[1,2],
     [3,4]])
arr1.shape

(2, 2)

In [30]:
arr1=np.array([[1,2,3],
     [3,4]])
print(arr1.shape)

ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 1 dimensions. The detected shape was (2,) + inhomogeneous part.

In [29]:
arr = np.array([
    [10, 20, 30],
    [40, 50, 60]
])
print(arr.shape)

(2, 3)


## Dimension
**arr.ndim**
- Dimension tells us the number of axes in an array.
- We can find the number of dimensions using ndim.
- In NumPy, dimensions are also called axes.

In [34]:
arr = np.array([
    [10, 20, 30],
    [40, 50, 60]
])
print(arr.ndim)


2


In [33]:
arr = np.array([10, 20, 30, 40])
print(arr.ndim)

1


In [4]:
arr = np.array([
    [[1, 2], [3, 4]],
    [[5, 6], [7, 8]]
])
print(arr.ndim)

3


## Size 
- size tells us the total number of elements in a NumPy array.
- We can check it using .size.

In [18]:
import numpy as np

arr = np.array([10, 20, 30, 40, 50])

print(arr.size)

5


In [19]:
arr = np.array([
    [10, 20, 30],
    [40, 50, 60]
])

print(arr.size)

6


## Data Type (dtype)
- dtype tells us the data type of the elements in a NumPy array.
- We can check it using dtype.
- NumPy automatically determines the data type while creating the array.

In [1]:
import numpy as np

arr = np.array([10, 20, 30, 40])

print(arr)
print(arr.dtype)


[10 20 30 40]
int64


In [20]:
arr = np.array([10.5, 20.5, 30.5])

print(arr.dtype)

float64


In [22]:
arr = np.array([10, 20.5, 30])

print(arr.dtype)

float64


In [23]:
arr = np.array(["apple", 20.5, 305])

print(arr.dtype)

<U32


In [3]:
arr = np.array(["Python", "SQL", "Power BI"])

print(arr.dtype)

<U8


### NumPy Data Types
- int – Integer numbers eg: np.array([10, 20, 30])
  - **int8  int16 int32 int64**
- float – Decimal numbers eg: np.array([10.5, 20.5, 30.5])
  - **float16
float32
float64**
- complex – Complex numbers eg: np.array([2+3j, 4+5j]) 
- bool – True / False eg: np.array([True, False, True])
  - **True / False**
- str / Unicode – Text values eg: np.array(["Python", "SQL", "Power BI"])
    - **< → Unicode
U → Unicode string
7 → maximum string length**
 
- object – Python objects / mixed-type values  eg: np.array([10, "Python", 20.5], dtype=object)

In [13]:
np.array([10, 20, 30])

array([10, 20, 30])

In [12]:
np.array([10.5, 20.5, 30.5])

array([10.5, 20.5, 30.5])

In [11]:
np.array([2+3j, 4+5j]) 

array([2.+3.j, 4.+5.j])

In [9]:
np.array([True, False, True])

array([ True, False,  True])

In [10]:
np.array(["Python", "SQL"])

array(['Python', 'SQL'], dtype='<U6')

In [24]:
np.array([10, "Python", 20.5], dtype=object)

array([10, 'Python', 20.5], dtype=object)

## Basic Matic Operations

In [30]:
arr=np.array([10,20,30,40,50])
print(f"Sum: {arr.sum()}")
print(f"Mean: {arr.mean()}")
print(f"Min: {arr.min()}")
print(f"Max: {arr.max()}")
print(f"std: {arr.std()}")

Sum: 150
Mean: 30.0
Min: 10
Max: 50
std: 14.142135623730951


# Comparision List vs Numpy Array 



In [48]:
py_list=[1,2,3,4]
np_arr=np.array([1,2,3,4])

#addition 
print("****** Addition *******")
print(py_list+[6,7,8]) # [1, 2, 3, 4, 6, 7, 8]
print(np_arr+np.array([6,7,8,9])) # [1, 2, 3, 4, 6, 7, 8]

#Multiply
print("\n\n****** Multiply *******")
print(py_list*2) # [1, 2, 3, 4, 1, 2, 3, 4]
print(np_arr*2) # [2 4 6 8]

# mixed 
print("\n\n****** Mixed *******")
mixed_list=[1,"hello",3.14,True]
print(mixed_list)

****** Addition *******
[1, 2, 3, 4, 6, 7, 8]
[ 7  9 11 13]


****** Multiply *******
[1, 2, 3, 4, 1, 2, 3, 4]
[2 4 6 8]


****** Mixed *******
[1, 'hello', 3.14, True]
